### ISSUE TITLE
Failed transport show support

### ISSUE THREAD

**Issue by arendjantetteroo** [alekitto/messenger-extra#13]
I tried the following command after setting up a failed transport with messenger:

```
 php bin/console messenger:failed:show                                                                                
  The "failed" receiver does not support listing or showing specific messages.  
```

I checked the symfony receiver, they have 2 specific interfaces to allow this behaviour:
`class DoctrineReceiver implements ReceiverInterface, MessageCountAwareInterface, ListableReceiverInterface`                          

I can add a PR for the mongo transport as i use it, interested?

**Comment by alekitto** [comment]
I wasn't aware of these interfaces.
A PR is always welcome! :)

**Comment by alekitto** [comment]
This should be fixed in https://github.com/alekitto/messenger-extra/commit/ab22ee4ca7226d6bdd2c9c7de1e95573a578a5d3.
Could you please confirm?

**Comment by alekitto** [comment]
No notice since 26 Feb. I'm considering this issue as resolved.
