### ISSUE TITLE
New tag release

### ISSUE THREAD

**Issue by franciscosantamaria** [alekitto/messenger-extra#15]
Hi, are you planning to create a new tag from master branch?
I want to use this package, but prefer to link to a tag instead of a specific commit or branch.  (Symfony 5 requirements).

Thanks for your time.

**Comment by alekitto** [comment]
Hi @franciscosantamaria,
I just tagged [version 2.0](https://github.com/alekitto/messenger-extra/releases/tag/2.0.0).

Hope this could be useful to you too!
