### ISSUE TITLE
MongoDB AuthenticationException

### ISSUE THREAD

**Issue by Spope** [alekitto/messenger-extra#19]
When connecting to an authenticated MongoDB server (dsn like : mongodb://user:pass@server:port/database_name) the MongoTransportFactory rebuilt the url as "mongodb://user:pass@server:port/" without the database name. This cause an AuthenticationException :

    In Delete.php line 141:
        Bulk write failed due to previous MongoDB\Driver\Exception\AuthenticationException: Authentication failed.

    In Delete.php line 141:
        Authentication failed.

Looks like adding `$params['path'] = '/' . $databaseName;` makes it work.

PS. Thanks for your lib !

PS2. My [authSource](https://docs.mongodb.com/manual/reference/connection-string/#urioption.authSource) is "admin", I tried to add "mongodb://user:pass@server:port/database_name?authSource=admin" to.

**Comment by Spope** [comment]
Ok, I had misunderstood authSource, it require to specify database associated to user's credentials (not mongo credential database), so in my case, authSource=database_name.

Closing, sorry about that.

**Comment by alekitto** [comment]
Hi @Spope, thank you for using this lib!

If you want/have enough time, please open a PR explaining how to deal with mongo authentication in README.md, to help other users using mongo transport with authentication enabled.
Thank you again.
