### ISSUE TITLE
mongodb auth issue with authSource not been taken from connection string

### ISSUE THREAD

**Issue by bitgandtter** [alekitto/messenger-extra#26]
This bug seems to be fixed on the master branch file https://github.com/alekitto/messenger-extra/blob/master/lib/Transport/Mongo/MongoTransportFactory.php#L44 but not on the latest release on branch 2.x https://github.com/alekitto/messenger-extra/blob/2.x/lib/Transport/Mongo/MongoTransportFactory.php#L44

Its preventing me from using it, can please this be merged into the 2.x branch?

**Comment by alekitto** [comment]
@bitgandtter You're right. I've just published a new release ([2.3.1](https://github.com/alekitto/messenger-extra/releases/tag/2.3.1)) with the fix you're referring to.
