### ISSUE TITLE
PostgreSql incompatibility for UuidBinaryOrderedTimeType

### ISSUE THREAD

**Issue by massimilianobraglia** [alekitto/messenger-extra#3]
Hey there,

we're facing a problem while inserting messages in our table.
As stated here https://github.com/ramsey/uuid/issues/179 and here https://github.com/ramsey/uuid-doctrine/issues/47#issuecomment-342748828, using `UuidBinaryOrderedTimeType` and `UuidBinaryType ` are intended primarly for  MySQL/MariaDB DBMS. Instead, for PostgreSql is intended the `UuidType`. 

In fact, the insert results in the following error:
```sql
INSERT INTO queue_api (id, published_at, body, headers, properties, priority, time_to_live, delayed_until) VALUES ('9a304ec0-7241-11e9-b7f6-0242ac12000c', '2019-05-09 10:02:49', '{"message_body":"the body"}', '{"type": "App\Messenge\FullyQualified\Name"}', '[]', 0, null, null)
```
`ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x72 0x42`

I have time to make a PR, but before a little discussion:
Explicitly checking the Database platform at this line seems not so elegant.
`\Kcs\MessengerExtra\Transport\Dbal\DbalSender::send#line79`

Any advice?

PS:
To reproduce this is really simple: just try to persist a new message with Symfony + Doctrine (and obviously Messenger with this bundle)

**Comment by alekitto** [comment]
Seems that binary (`LARGE_OBJECT`) flags was not set in `getBindingType` method of none of the uuid-doctrine types. This leads to that error in postgresql as the server does not expect binary values.

Workin' on it

**Comment by massimilianobraglia** [comment]
Exactly. The merged a PR on that and reverted because is platform dependant. (you can find a closed PR on ramsey/uuid-doctrine)

**Comment by alekitto** [comment]
Should be fixed in master (ref: https://github.com/alekitto/messenger-extra/commit/70779b4cfb19965f69392ee5acf63d92beadeed7)

**Comment by massimilianobraglia** [comment]
Ok, thank you. I'll let you know if it solves my issue

**Comment by massimilianobraglia** [comment]
@alekitto seems to work fine! Thank you 😄
