### ISSUE TITLE
Problems with Symfony 4.4 implementation

### ISSUE THREAD

**Issue by vkost** [alekitto/messenger-extra#4]
Hi, 

First, let me thank you for the work you invested in this extension - I could probably make something similar myself but this is a major time-saver.

I installed the bundle under Symfony 4.4, knowing that it's in dev status, but willing to try. I ran into one issue that I patched to test the implementation, and I thought I should report it. In MongoSender.php line 67, there was a reference to a missing array key, $encodedMessage['headers']. Digging into the issue, I realised that old serializers were inserting this key into the resulting array, but the latest PhpSerializer (introduced in Symfony 4.3) is not inserting it so the code was crashing. I did not investigate further (for example, I'm not sure if the headers have any specific purpose or not) but replacing $encodedMessage['headers'] with [] made the code work, and as far as I can tell, it's working just fine. 

Let me know if this means anything. I will easily for the repo and apply the fix for myself, but if I learn more I may be able to make a pull request to make the extension usable by others. As far as I saw, there's no other way to use Mongo as a transport at the moment.

Thanks,
Vic

**Comment by arendjantetteroo** [comment]
See #5 , i just came across the same issue
